### ISSUE TITLE
error and bad files

### ISSUE THREAD

**Issue by sajad1382** [danog/MadelineProtoDocs#16]
why madeline.php and... will copy in root folder and public_html\folder?
and this error in line 100
        if (\strpos($contents, 'new \danog\MadelineProto\Server') && \in_array($contents, [\file_get_contents('https://github.com/danog/MadelineProtoPhar/raw/2270bd9a94d168a5e6731ffd7e61821ea244beff/mtproxyd'), \file_get_contents('https://github.com/danog/MadelineProtoPhar/raw/7cabb718ec3ccb79e3c8e3d34f5bccbe3f63b0fd/mtproxyd')]) && ($mtproxyd = \file_get_contents('https://phar.madelineproto.xyz/mtproxyd?v=new'))) {
            \file_put_contents($file, $mtproxyd);

            return;
        }

**Comment by danog** [comment]
Send full logs, this doesn't help at all.
