### ISSUE TITLE
Get people nearby

### ISSUE THREAD

**Issue by frech87** [danog/MadelineProtoDocs#25]
Hi. It is great job. But I can not use getLocated
`$MadelineProto = new \danog\MadelineProto\API('session.madeline');
        $MadelineProto->start();
        $inputGeoPoint = ['_' => 'inputGeoPoint', 'lat' => 55.753930, 'long' => 37.615714];
        $location = $MadelineProto->contacts->getLocated(['background'=> false, 'geo_point' => $inputGeoPoint, 'self_expires' => 0]);
        dd($location);`
But return error : INVALID INPUT
`array:7 [▼
  "_" => "updates"
  "updates" => []
  "users" => []
  "chats" => []
  "date" => 1611055246
  "seq" => 0
  "request" => array:12 [▼
    "apifactory" => true
    "datacenter" => 2
    "_" => "contacts.getLocated"
    "type" => "Updates"
    "contentRelated" => true
    "promise" => Amp\Deferred {#3975 ▶}
    "method" => true
    "unencrypted" => false
    "body" => array:3 [▼
      "background" => false
      "geo_point" => array:3 [▼
        "_" => "inputGeoPoint"
        "lat" => 55.75393
        "long" => 37.615714
      ]
      "self_expires" => 0
    ]
    "serialized_body" => b"D¼HÓ\x01\x00\x00\x00É¬·ó”¼:Ç€àK@<Øb·ÏÎB@\x00\x00\x00\x00"(INVALID INPUT)
    "sent" => 1611055247
    "tries" => 0
  ]
]`

**Comment by danog** [comment]
You must yield the result.
