### ISSUE TITLE
How I do generating phone_code_hash to be passing in to auth.signIn() method

### ISSUE THREAD

**Issue by alimin002** [danog/MadelineProtoDocs#26]
I am strugling to use Method: auth.signIn() but I have no ide how to generate one of it's parameter called phone_code_hash
this is the usage of the method above from official documentation https://docs.madelineproto.xyz/API_docs/methods/auth.signIn.html

`_$auth_Authorization = $MadelineProto->auth->signIn(['phone_number' => 'string', 'phone_code_hash' => 'string', 'phone_code' => 'string', ]);`

please help me to properly generate phone_code_hash in madeline proto @danog

**Comment by danog** [comment]
please follow https://docs.madelineproto.xyz/docs/LOGIN.html
