### ISSUE TITLE
channels.editBanned gives BOT_METHOD_INVALID

### ISSUE THREAD

**Issue by hoermann-p** [danog/MadelineProtoDocs#27]
The Page in the documentation:

https://docs.madelineproto.xyz/API_docs/methods/channels.editBanned.html

States that this function can be used by a Bot, however it seems that it can not be used by a bot as I get BOT_METHOD_INVALID as exception.

Is this a issue in my code or is the documentation wrong?

**Comment by danog** [comment]
Mm, could I get a full trace pls
