### ISSUE TITLE
MSG_ID_INVALID error in startBot method

### ISSUE THREAD

**Issue by ali-sajed** [danog/MadelineProtoDocs#29]
Why does this error occur?

code:

$MadelineProto->messages->startBot([
        'bot' => '@SpamBot',
        'start_param' => 'string'
    ]);

log:

Serialization:  	Connected to IPC socket!
Exception:      	Telegram returned an RPC error: Invalid message ID provided (400) (MSG_ID_INVALID), caused by phar...
Revision: aeed13260f3a397f11564a1cfb706e25663422db-74<br>
<br>
TL trace:<br>
<br><br>
Client.php(237):    	__call("methodCallAsyncRead",["messages.startBot",{"bot":"@SpamBot","start_param":"string"},{"apifactory":true}])<br><br>
AbstractAPIFactory.php(183):	methodCallAsyncRead("messages.startBot",{"bot":"@SpamBot","start_param":"string"},{"apifactory":true})<br><br>
__call_async()<br><br>
<br><br>
Previous TL trace:<br><br>
['messages.startBot']<br><br>
CallHandler.php(59):	methodCallAsyncRead("messages.startBot",{"bot":"@SpamBot","start_param":"string"},{"apifactory":true})<br><br>
Server.php(241):    	methodCallAsyncRead("messages.startBot",{"bot":"@SpamBot","start_param":"string"},{"apifactory":true})<br><br>
clientRequest()<br><br>
<br><br>
Previous TL trace:<br><br>
['messages.startBot']<br><br>
ResponseHandler.php(185):	handleRpcError({},{"_":"rpc_error","error_code":400,"error_message":"MSG_ID_INVALID"})<br><br>
ResponseHandler.php(67):	handleResponse({})<br><br>
Driver.php(102):    	handleMessages("hjxt",null)<br><br>
Driver.php(61):     	tick()<br><br>
Loop.php(87):       	run()<br><br>
Tools.php(313):     	run({})<br><br>
entry.php(99):      	wait({})<br><br>
entry.php(122):     	{closure}()<br><br>

**Comment by danog** [comment]
This should be fixed in the latest version of MadelineProto 7, if it isn't please open a new issue at https://github.com/danog/MadelineProto
